from datetime import datetime

from pydantic import BaseModel, model_validator
from typing import List, Optional
from app.modules.authenticity.schemas import AuthenticitySummary


class DiscoverCreatorsRequest(BaseModel):
    """
    What a brand is searching against.

    Two ways in, and they are not equal:

    * **`campaign_id`** — run against a campaign the brand already created. Every
      criterion is then read from that record, so the search matches the offer a
      creator will actually receive.
    * **The loose fields below** — an ad-hoc search for a brand that has not
      created a campaign yet.

    The ad-hoc path existed first and is kept because a brand should be able to
    look around before committing to a campaign. But it re-asks for niche, goal,
    location and platforms that a campaign already states, and nothing connects
    the shortlist it produces to the offer that eventually goes out. When
    `campaign_id` is present the loose fields are ignored outright rather than
    merged, so there is never a question of which value won.
    """

    #: A campaign owned by the requesting brand. Ownership is enforced server-side.
    campaign_id: int | None = None

    #: Required only for an ad-hoc search. A campaign supplies its own.
    niche: str | None = None
    budget_range: str = "Mid"  # Low | Mid | High
    campaign_goal: str = "Awareness"  # Awareness | Sales | Engagement
    target_location: str | None = None
    target_languages: list[str] | None = None
    platform_preferences: list[str] | None = None

    @model_validator(mode="after")
    def _needs_a_niche_or_a_campaign(self) -> "DiscoverCreatorsRequest":
        if self.campaign_id is None and not (self.niche or "").strip():
            raise ValueError("Provide either campaign_id or niche")
        return self


class RankedCreator(BaseModel):
    """
    One creator in a discovery result.

    The profile fields below are filled **from the database**, never from the
    model's output — the model may only decide fit and reasoning, not facts
    about a creator. Previously the response carried just an id and a name, so
    the brand's screen showed "Creator 7 / ID: 7" with no follower count,
    engagement rate or handle to judge by.
    """

    creator_id: str
    creator_name: str | None = None
    fit_level: str
    score_reasoning: list[str] | None = None
    risks: list[str] | None = None
    recommended_campaign_type: str | None = None

    # --- Verified profile data (server-sourced) ---
    category: str | None = None
    location: str | None = None
    primary_platform: str | None = None
    bio: str | None = None
    instagram_username: str | None = None
    instagram_url: str | None = None
    youtube_username: str | None = None
    youtube_url: str | None = None
    avatar_url: str | None = None
    followers: int | None = None
    subscribers: int | None = None
    avg_likes: int | None = None
    avg_comments: int | None = None
    engagement_rate: float | None = None
    is_verified: bool | None = None
    #: Headline Authenticity Score (V3). Null until the creator has been scored.
    authenticity: AuthenticitySummary | None = None


class DiscoverCreatorsResponse(BaseModel):
    ranked_creators: list[RankedCreator]
    final_recommendation: str | None = None

    #: Which campaign this shortlist was produced for, when one was used. The
    #: brand owns the campaign, so echoing it back discloses nothing.
    campaign_id: int | None = None
    campaign_name: str | None = None

    #: "campaign" or "custom". The UI says which criteria produced the result so
    #: a brand is never guessing whether it searched against its real brief.
    criteria_source: str = "custom"

    #: Set when a stated follower floor could not be honoured because nobody
    #: cleared it. The results are then unfiltered, and saying so is better than
    #: quietly returning people the brand already ruled out.
    follower_floor_relaxed: bool = False


class BrandDealOpportunity(BaseModel):
    """
    An anonymised opportunity shown to a creator.

    Two classes of field, deliberately separated:

    * **Verified** — `budget_range` comes from what the brand actually set on
      its profile.
    * **Indicative** — `compensation`, `timeline` and `deliverables` are
      generated by the model. No brand has agreed to them. They were previously
      rendered as though they were an offer, which is how a creator ends up
      acting on a number nobody promised. `terms_are_estimated` exists so the UI
      cannot forget to say so.
    """

    opportunity_id: str

    # --- Real terms, when the opportunity came from a campaign ---
    #: Present only for campaign-backed opportunities. The brand's actual fee.
    budget_per_creator: int | None = None
    currency: str | None = None
    #: The brand's actual deadline, not "within 3 weeks".
    deadline: str | None = None
    #: Short creator-facing description of the collaboration.
    what_to_expect: str | None = None
    #: Why the AI thinks this creator fits.
    why_it_fits: list[str] | None = None

    #: Set by the brand: "Low" | "Mid" | "High". Never model-generated.
    budget_range: str | None = None
    #: False when every commercial term came from a real campaign. True for
    #: legacy profile-derived opportunities, where the model estimated them.
    terms_are_estimated: bool = True
    #: Whether the creator has already registered interest.
    interested: bool = False
    fit_level: str | None = None
    industry_hint: str | None = None
    campaign_type: str | None = None
    campaign_requirements: str | None = None
    compensation: str | None = None
    timeline: str | None = None
    deliverables: list[str] | None = None
    status: str | None = "open"


class BrandDealsResponse(BaseModel):
    opportunities: list[BrandDealOpportunity]
    total: int
    #: When this batch was generated, and whether it now predates the creator's
    #: current numbers. `brand_deals_generated_at` was written and never read,
    #: so a creator could be looking at months-old matches with no indication.
    generated_at: datetime | None = None
    is_stale: bool = False


class CreatorSummaryResponse(BaseModel):
    #: See BrandDealsResponse — same staleness contract.
    generated_at: datetime | None = None
    is_stale: bool = False
    creator_id: str | None = None
    summary: str | None = None
    strengths: list[str] | None = None
    improvement_areas: list[str] | None = None
    best_brand_categories: list[str] | None = None
    recommended_content_formats: list[str] | None = None


class InterestRequest(BaseModel):
    """Creator registering interest in an opportunity."""
    opportunity_id: str
    message: str | None = None


class InterestedCreator(BaseModel):
    """A creator who has raised their hand, as the brand sees them."""
    interest_id: int
    creator_id: int
    creator_name: str | None = None
    #: Disclosed only because the creator opted in by expressing interest.
    email: str
    category: str | None = None
    location: str | None = None
    instagram_username: str | None = None
    youtube_username: str | None = None
    followers: int | None = None
    engagement_rate: float | None = None
    authenticity: AuthenticitySummary | None = None
    message: str | None = None
    campaign_type: str | None = None
    created_at: datetime


class InterestedCreatorsResponse(BaseModel):
    creators: list[InterestedCreator]
    total: int


class CreatorProfileForBrand(BaseModel):
    """
    A creator's profile as a brand sees it (V3 Phase 3) — the page behind
    "View complete profile". Public stats and the Authenticity headline only;
    contact details stay private until the creator expresses interest.
    """
    creator_id: int
    creator_name: str | None = None
    category: str | None = None
    location: str | None = None
    primary_platform: str | None = None
    bio: str | None = None
    instagram_username: str | None = None
    instagram_url: str | None = None
    youtube_username: str | None = None
    youtube_url: str | None = None
    followers: int | None = None
    subscribers: int | None = None
    avg_likes: int | None = None
    avg_comments: int | None = None
    engagement_rate: float | None = None
    is_verified: bool | None = None
    authenticity: AuthenticitySummary | None = None
