"""Add deal_deliveries table

Delivery tracking against an agreed offer (V2 §1.4). See
app/modules/deals/deliveries.py for why submissions are immutable and why
completion is derived rather than stored.

HAND-WRITTEN, not autogenerated, per the convention in d81f4a2c9b03.

Revision ID: b2f6a8d13c47
Revises: e7b3d9c45a18
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "b2f6a8d13c47"
down_revision: Union[str, Sequence[str], None] = "e7b3d9c45a18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "deal_deliveries"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.Column("submitted_by_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="submitted"),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["offer_id"], ["deal_offers.id"],
            name="deal_deliveries_offer_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"], ["users.id"],
            name="deal_deliveries_submitted_by_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"], ["users.id"],
            name="deal_deliveries_reviewed_by_id_fkey", ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], [f"{TABLE}.id"],
            name="deal_deliveries_supersedes_id_fkey", ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="deal_deliveries_pkey"),
    )
    op.create_index("ix_deal_deliveries_offer_id", TABLE, ["offer_id"])
    op.create_index("ix_deal_deliveries_submitted_by_id", TABLE, ["submitted_by_id"])
    op.create_index("ix_deal_deliveries_status", TABLE, ["status"])
    op.create_index("ix_deal_deliveries_offer_created", TABLE, ["offer_id", "created_at"])


def downgrade() -> None:
    op.drop_table(TABLE)
