"""Add deal_reviews table

Two-way reviews after a deal is delivered (V2 §1.5). See
app/modules/deals/reviews.py for why reveal is double-blind and computed at
read time rather than stored.

HAND-WRITTEN, not autogenerated, per the convention in d81f4a2c9b03.

Revision ID: c8e1b47f2a93
Revises: b2f6a8d13c47
Create Date: 2026-09-30
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "c8e1b47f2a93"
down_revision: Union[str, Sequence[str], None] = "b2f6a8d13c47"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "deal_reviews"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("author_role", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["opportunity_interests.id"],
            name="deal_reviews_interest_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"],
            name="deal_reviews_author_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"], ["users.id"],
            name="deal_reviews_subject_id_fkey", ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="deal_reviews_pkey"),
        # One review per person per deal, guaranteed by the database rather than
        # by a handler check that a concurrent double-submit would slip past.
        sa.UniqueConstraint("interest_id", "author_id", name="uq_review_author_interest"),
    )
    op.create_index("ix_deal_reviews_interest_id", TABLE, ["interest_id"])
    op.create_index("ix_deal_reviews_author_id", TABLE, ["author_id"])
    op.create_index("ix_deal_reviews_subject_id", TABLE, ["subject_id"])
    op.create_index("ix_deal_reviews_subject", TABLE, ["subject_id"])


def downgrade() -> None:
    op.drop_table(TABLE)
