"""Add messages table

In-app messaging between a brand and a creator, scoped to the interest that
introduced them (V2 §1.1). See app/modules/messaging/models.py for the
rationale.

HAND-WRITTEN, not autogenerated, per the convention in d81f4a2c9b03.

Revision ID: d4f8a2c1e9b7
Revises: a1c9e4f2b8d6
Create Date: 2026-08-22
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "d4f8a2c1e9b7"
down_revision: Union[str, Sequence[str], None] = "a1c9e4f2b8d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "messages"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["opportunity_interests.id"],
            name="messages_interest_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"],
            name="messages_sender_id_fkey", ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="messages_pkey"),
    )
    op.create_index("ix_messages_interest_id", TABLE, ["interest_id"])
    op.create_index("ix_messages_sender_id", TABLE, ["sender_id"])
    op.create_index("ix_messages_interest_created", TABLE, ["interest_id", "created_at"])


def downgrade() -> None:
    op.drop_table(TABLE)
