"""Add deal_offers table

Deal terms between one brand and one creator (V2 §1.2) — an immutable chain of
offers anchored on an interest. See app/modules/deals/offers.py for why offers
are never edited in place.

HAND-WRITTEN, not autogenerated, per the convention in d81f4a2c9b03.

Revision ID: e7b3d9c45a18
Revises: d4f8a2c1e9b7
Create Date: 2026-09-26
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e7b3d9c45a18"
down_revision: Union[str, Sequence[str], None] = "d4f8a2c1e9b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE = "deal_offers"


def upgrade() -> None:
    if TABLE in sa.inspect(op.get_bind()).get_table_names():
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interest_id", sa.Integer(), nullable=False),
        sa.Column("proposed_by_id", sa.Integer(), nullable=False),
        sa.Column("proposed_by_role", sa.String(), nullable=False),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        # Numeric rather than Float — money that round-trips through binary
        # floating point eventually disagrees with somebody's invoice.
        sa.Column("fee", sa.Numeric(12, 2), nullable=False),
        sa.Column("currency", sa.String(), nullable=False, server_default="INR"),
        sa.Column("deliverables", sa.Text(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False, server_default="proposed"),
        # Null until the payment phase; the rate in force at acceptance gets
        # frozen here so a later rate change cannot rewrite an agreed deal.
        sa.Column("commission_rate_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("responded_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["interest_id"], ["opportunity_interests.id"],
            name="deal_offers_interest_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_id"], ["users.id"],
            name="deal_offers_proposed_by_id_fkey", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["responded_by_id"], ["users.id"],
            name="deal_offers_responded_by_id_fkey", ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], [f"{TABLE}.id"],
            name="deal_offers_supersedes_id_fkey", ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="deal_offers_pkey"),
    )
    op.create_index("ix_deal_offers_interest_id", TABLE, ["interest_id"])
    op.create_index("ix_deal_offers_proposed_by_id", TABLE, ["proposed_by_id"])
    op.create_index("ix_deal_offers_status", TABLE, ["status"])
    op.create_index("ix_deal_offers_interest_created", TABLE, ["interest_id", "created_at"])

    # One agreed deal per interest, guaranteed by the database. The handler also
    # checks, but a read-then-write check loses a genuine race; this cannot.
    # Partial-index syntax is identical on PostgreSQL and SQLite, so one
    # statement covers production and the test suite.
    op.create_index(
        "uq_deal_offers_one_accepted", TABLE, ["interest_id"],
        unique=True, postgresql_where=sa.text("status = 'accepted'"),
        sqlite_where=sa.text("status = 'accepted'"),
    )


def downgrade() -> None:
    op.drop_table(TABLE)
